stages:
  - test
  - build

cache:
  key: one-key-to-rule-them-all
  paths:
    - node_modules/

before_script:
  - asdf install
  - yarn install

test:
  script:
    - yarn run lint
    - yarn run lint:style
  except:
    - develop
    - staging
    - master

deploy_staging:
  stage: build # 对应stages上的job名称
  script:
    - yarn build:staging:mp-weixin
    - yarn deploy:staging:mp-weixin
  only:
    - staging
  tags:
    - mac-shell-runner

deploy_production:
  stage: build # 对应stages上的job名称
  script:
    - yarn build:production:mp-weixin
    - yarn deploy:production:mp-weixin
  only:
    - master
  tags:
    - mac-shell-runner
